---
extends: "@spalger/personal/es6"

env:
  node: true

settings:
  import/resolver: webpack

rules:
  comma-dangle: off
  semi: off
  func-names: off
  no-var: off
  vars-on-top: off
  new-cap: off
  global-require: off
  no-param-reassign: off
  padded-blocks: off
  brace-style: off
  consistent-return: off
  default-case: off
  dot-notation: off
  eqeqeq: warn
  max-len: off
  no-cond-assign: off
  no-console: off
  no-else-return: off
  no-empty: off
  no-restricted-syntax: warn
  no-shadow: warn
  no-undef: warn
  no-underscore-dangle: off
  no-unused-expressions: warn
  no-unused-vars: warn
  no-use-before-define: off
  object-shorthand: off
  one-var: off
  one-var-declaration-per-line: off
  prefer-arrow-callback: off
  prefer-rest-params: off
  prefer-template: off
  quote-props: off
  yoda: off
  no-restricted-properties: warn
  no-prototype-builtins: warn
  prefer-spread: off
  import/no-dynamic-require: off
  import/no-internal-modules: off
  import/newline-after-import: off
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - "**/elasticsearch-js/{test,scripts,webpack_config,grunt}/**/*.js"
        - "**/elasticsearch-js/Gruntfile.js"