---
# yaml-language-server: $schema=https://json.schemastore.org/catalog-info.json
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: elasticsearch-js
spec:
  type: library
  owner: group:clients-team
  lifecycle: production

---
# yaml-language-server: $schema=https://gist.githubusercontent.com/elasticmachine/988b80dae436cafea07d9a4a460a011d/raw/e57ee3bed7a6f73077a3f55a38e76e40ec87a7cf/rre.schema.json
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: elasticsearch-js-integration-tests
  description: Elasticsearch JavaScript client integration tests
spec:
  type: buildkite-pipeline
  owner: group:clients-team
  system: buildkite
  implementation:
    apiVersion: buildkite.elastic.dev/v1
    kind: Pipeline
    metadata:
      name: Elasticsearch JavaScript client integration tests
    spec:
      repository: elastic/elasticsearch-js
      pipeline_file: .buildkite/pipeline.yml
      teams:
        clients-team:
          access_level: MANAGE_BUILD_AND_READ
        everyone:
          access_level: READ_ONLY
      cancel_intermediate_builds: true
      cancel_intermediate_builds_branch_filter: '!main'
      schedules:
        main_semi_daily:
          branch: 'main'
          cronline: '*/12 * * *'
        8_8_semi_daily:
          branch: '8.8'
          cronline: '*/12 * * *'
        8_7_daily:
          branch: '8.7'
          cronline: '@daily'
        8_6_daily:
          branch: '8.6'
          cronline: '@daily'
        7_17_daily:
          branch: '7.17'
          cronline: '@daily'
