---
steps:
  - label: ":elasticsearch: :javascript: ES JavaScript ({{ matrix.nodejs }})"
    agents:
      provider: "gcp"
    env:
      NODE_VERSION: "{{ matrix.nodejs }}"
      TEST_SUITE: "platinum"
      STACK_VERSION: 9.0.0
      GITHUB_TOKEN_PATH: "secret/ci/elastic-elasticsearch-js/github-token"
    matrix:
      setup:
        nodejs:
          - "18"
          - "20"
          - "22"
    command: ./.buildkite/run-tests.sh
    artifact_paths: "./junit-output/junit-*.xml"
  - wait: ~
    continue_on_failure: true
  - label: ":junit: Test results"
    agents:
      provider: "gcp"
      image: family/core-ubuntu-2204
    plugins:
      - junit-annotate#v2.6.0:
          artifacts: "junit-output/junit-*.xml"
          job-uuid-file-pattern: "junit-(.*).xml"
          fail-build-on-error: true
          failure-format: file
