---
agents:
  provider: "gcp"
  image: family/core-ubuntu-2204
  memory: "8G"
  cpu: "2"

steps:
  - label: ":elasticsearch: :javascript: ES JavaScript ({{ matrix.nodejs }})"
    env:
      NODE_VERSION: "{{ matrix.nodejs }}"
      TEST_SUITE: "platinum"
      STACK_VERSION: 9.1.0
      GITHUB_TOKEN_PATH: "secret/ci/elastic-elasticsearch-js/github-token"
      TEST_ES_STACK: "1"
    matrix:
      setup:
        nodejs:
          - "20"
          - "22"
          - "24"
    command: ./.buildkite/run-tests.sh
    artifact_paths: "./junit-output/junit-*.xml"
  - wait: ~
    continue_on_failure: true
  - label: ":junit: Test results"
    plugins:
      - junit-annotate#v2.7.0:
          artifacts: "junit-output/junit-*.xml"
          job-uuid-file-pattern: "junit-(.*).xml"
          fail-build-on-error: true
          failure-format: file
