version: '3.2'
services:
  client:
    image: docker.elastic.co/clients/elasticsearch-js:${NODE_JS_VERSION:-8}
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
          NODE_JS_VERSION: ${NODE_JS_VERSION:-8}
    environment:
      - "TEST_ES_SERVER=http://elasticsearch:9200"
    volumes:
      - .:/usr/src/app
      - esvol:/tmp
    networks:
      - esnet
    depends_on:
      - elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION:-6.2.4}
    volumes:
      - esvol:/tmp
    networks:
      - esnet
    environment:
      - path.repo=/tmp
      - "repositories.url.allowed_urls=http://*"
      - node.attr.testattr=test
      - bootstrap.memory_lock=false
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - "http.max_content_length=5mb"
networks:
  esnet:
volumes:
  esvol:
