#!/usr/bin/env bash

#
# Runs the client tests via Docker with the expectation that the required
# environment variables have already been exported before running this script.
#
# The required environment variables include:
#
#   - $ELASTICSEARCH_VERSION
#   - $NODE_JS_VERSION
#

# TODO: implement the docker-based testing
echo docker-compose [...]
