---
name: 🚀 Feature Proposal
description: Submit a proposal for a new feature
labels: ["Category: Feature"]
body:
  - type: markdown
    attributes:
      value: |
        It's not uncommon that somebody already opened an issue or in the best case it's already fixed but not merged. That's the reason why you should [search](https://github.com/elastic/elasticsearch-js/issues) at first before submitting a new one.

        **Please read this entire template before posting any issue. If you ignore these instructions
        and post an issue here that does not follow the instructions, your issue might be closed,
        locked, and assigned the `Category: Not an issue` label.**

  - type: textarea
    id: feature-proposal
    attributes:
      label: 🚀 Feature Proposal
      description: A clear and concise description of what the feature is.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please outline the motivation for the proposal.

  - type: textarea
    id: example
    attributes:
      label: Example
      description: Please provide an example for how this feature would be used.
