[[extensions]]
== Extensions

This page aims to list useful extensions for the elasticsearch.js client provided by the elasticsearch community. If you would like to list your extension here please submit a pull request against https://github.com/elastic/elasticsearch-js/blob/master/docs/extending_core_components.asciidoc[the source code for this page].

For information about writing extensions, check out the <<extending_core_components>> page.

=== superagent-elasticsearch
This `Connection` class allows you to send all requests from an elasticsearch.js `Client` instance with https://github.com/visionmedia/superagent[superagent]. `superagent` has support for all sorts of authentication strategies (eg. kerberos, in-house CAs, etc.), but also supports a `beforeEachRequest` hook powers all kinds of per-request tweaking.

superagent-elasticsearch is available on https://www.npmjs.com/package/superagent-elasticsearch[npm].

=== http-aws-es
Makes elasticsearch-js compatible with https://aws.amazon.com/elasticsearch-service/[Amazon ES]. It uses the https://www.npmjs.com/package/aws-sdk[aws-sdk] to make signed requests to an Amazon ES endpoint.

http-aws-es is available on https://www.npmjs.com/package/http-aws-es[npm].

=== elasticsearch-scrolltoend
This module provides a `scrollToEnd` function which allows for processing each batch while scrolling search results.

elasticsearch-scrolltoend is available on https://www.npmjs.com/package/elasticsearch-scrolltoend[npm].

=== elasticsearch-deletebyquery
This module provides the `deleteByQuery` method which was removed from the core API in ES 2.0.0. For those with the https://www.elastic.co/guide/en/elasticsearch/plugins/2.0/plugins-delete-by-query.html[Delete-by-query] installed, this will bring back that feature to your Elasticsearch-js client.

elasticsearch-deletebyquery is available on https://www.npmjs.com/package/elasticsearch-deletebyquery[npm].
