[[installation]]
== Installation

This page guides you through the installation process of the client.

To install the latest version of the client, run the following command:

[source,sh]
----
npm install @elastic/elasticsearch
----

To install a specific major version of the client, run the following command:

[source,sh]
----
npm install @elastic/elasticsearch@<major>
----

To learn more about the supported major versions, please refer to the 
<<js-compatibility-matrix>>.

[discrete]
[[js-compatibility-matrix]]
=== Compatibility matrix

The minimum supported version of Node.js is `v8`.

The library is compatible with all {es} versions since 5.x. We recommend you to
use the same major version of the client as the {es} instance that you are
using.


[%header,cols=2*]
|===
|{es} Version
|Client Version

|`master`
|`master`

|`7.x`
|`7.x`

|`6.x`
|`6.x`

|`5.x`
|`5.x`
|===


[discrete]
==== Browser

WARNING: There is no official support for the browser environment. It exposes
your {es} instance to everyone, which could lead to security issues. We
recommend you to write a lightweight proxy that uses this client instead.