module.exports = {
  get '_default'() { return require('./6_6'); },
  get '6.6'() { return require('./6_6'); },
  get '6.5'() { return require('./6_5'); },
  get '6.4'() { return require('./6_4'); },
  get '6.3'() { return require('./6_3'); },
  get '6.2'() { return require('./6_2'); },
  get '6.1'() { return require('./6_1'); },
  get '6.0'() { return require('./6_0'); },
  get '5.6'() { return require('./5_6'); },
  get '2.4'() { return require('./2_4'); },
  get '1.7'() { return require('./1_7'); },
  get '0.90'() { return require('./0_90'); },
  get '6.7'() { return require('./6_7'); },
  get '7.0'() { return require('./7_0'); },
  get '7.x'() { return require('./7_x'); },
  get 'master'() { return require('./master'); },
};
