name: Automerge

on:
  pull_request_review:
    types:
      - submitted

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    steps:
      - uses: reitermarkus/automerge@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          merge-method: squash
          pull-request-author-associations: OWNER
          review-author-associations: OWNER,CONTRIBUTOR
