---
name: "Auto-approve codegen PRs"
on: pull_request_target

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: github.actor == 'elasticmachine'
    steps:
      - uses: hmarr/auto-approve-action@v4
