name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@076f02ba436863237d90f1b7e7bc6b7a91eff4e3 # v1
    with:
      enable-vale-linting: true
