name: docs-preview-cleanup
on:
  pull_request_target:
    branches: [main]
    types: [closed]
permissions:
  contents: none
  deployments: write
  id-token: write
jobs:
  cleanup:
    uses: elastic/docs-actions/.github/workflows/docs-preview-cleanup.yml@e1608f9d7c62bc4c59ab21fc691809351b1a31aa # v1
