name: docs-build
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  merge_group: ~
permissions:
  contents: read
  pull-requests: read
jobs:
  build:
    uses: elastic/docs-actions/.github/workflows/docs-build.yml@4c0d4482b9b8ca8a3e4f2d99f834cbc7e95974c8 # v1
    with:
      enable-vale-linting: true
