---
name: Apply PR changes to serverless
on:
  pull_request_target:
    types:
      - closed
      - labeled

jobs:
  apply-patch:
    name: Apply patch
    runs-on: ubuntu-latest
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        (
          github.event.action == 'closed'
          && contains(github.event.pull_request.labels.*.name, 'apply-to-serverless')
        )
        ||
        (
          github.event.action == 'labeled'
          && github.event.label.name == 'apply-to-serverless'
        )
      )
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          repository: elastic/elasticsearch-js
          ref: main
          path: stack
          fetch-depth: 0
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
          repository: elastic/elasticsearch-serverless-js
          ref: main
          path: serverless
      - name: Apply patch from stack to serverless
        id: apply-patch
        run: $GITHUB_WORKSPACE/stack/.github/workflows/serverless-patch.sh
      - uses: peter-evans/create-pull-request@67ccf781d68cd99b580ae25a5c18a1cc84ffff1f # v7
        with:
          token: ${{ secrets.GH_TOKEN }}
          path: serverless
          title: "Apply patch from elastic/elasticsearch-js#${{ github.event.pull_request.number }}"
          commit-message: "Apply patch from elastic/elasticsearch-js#${{ github.event.pull_request.number }}"
          body-path: /tmp/pr_body
          draft: "${{ steps.apply-patch.outputs.PR_DRAFT }}"
          add-paths: ":!*.rej"
